### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#1]
Support a key based authorization.

Some ideas to work through:
* Should it use the same rubygems.org key?
* If not, should there be a command like gemstash push `gem`, which uses its own key?
* Should we direct user to specify a separate key manually?
* Maybe gemstash push `gem` is an alias for gem push, but uses a separate key file and passes it directly to gem command?
* Should key be protected on server?
* How to authorize on the server? gemstash authorize `key`?
* `gem yank` doesn't seem to work with a remote host... maybe support gemstash yank `gem` -v `version`?

**Comment by pcarranza** [comment]
What kind of authorizations should we support?

Are we talking about read only or also writing permissions?

I'm not sure if I want gemstash (the man in the middle) to handle my auth keys with write permissions to some server

**Comment by smellsblue** [comment]
My thoughts here are purely for private gems, I don't think it makes sense to push to an upstream through gemstash.

**Comment by smellsblue** [comment]
I've added a key based authorization mechanism. A new key can be created via `gemstash authorize` and the new key can be used to push with.
