### ISSUE TITLE
/versions and /info/* are redirected to rubygems.org

### ISSUE THREAD

**Issue by derektamsen** [bundler/gemstash#100]
Gemstash is currently redirecting requests for `/versions` to https://rubygems.org/versions instead of the correct https://index.rubygems.org/versions. The endpoint for `/info/*` should also be updated to redirect to https://index.rubygems.org/info/*.

```
bundle update --verbose
HTTP GET https://internal.gemstash.server/versions
HTTP 302 Found
HTTP GET https://rubygems.org/versions
HTTP 200 OK
HTTP GET https://internal.gemstash.server/versions
HTTP 302 Found
HTTP GET https://rubygems.org/versions
HTTP 200 OK
The checksum of /versions does not match the checksum provided by the server! Something is wrong (local checksum is "\"f3e85d51952e0136d9a61006a82ab686\"", was expecting "W/\"f3e85d51952e0136d9a61006a82ab686\"").
HTTP GET https://internal.gemstash.server/api/v1/dependencies
HTTP 200 OK
```

This also has the side effect of causing a checksum mismatch due to rubygems.org serving weak ETags for the `/versions` endpoint. See https://github.com/bundler/bundler/issues/4764 for reference.

**Comment by smellsblue** [comment]
I think I can get a fix for this relatively quickly. Does this result in a bundle failure, or just the error outputs?

**Comment by derektamsen** [comment]
I think it is just displaying a warning. However, it is a raise in the bundler code: https://github.com/bundler/bundler/blob/master/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb#L62

**Comment by smellsblue** [comment]
I tried bundling with verbose with and without my #102 branch, and that seems to have fixed it. I'd like to get a review of the changes, and then I'll push a new version of the gem once it gets merged into master :-)

Thanks for reporting this!

**Comment by smellsblue** [comment]
@derektamsen This is now in master and the new `1.0.2` version of the gem :-)

**Comment by derektamsen** [comment]
Great! Thanks for fixing this so quickly.
