### ISSUE TITLE
Are *.gem files cached for 30 minutes or indefinitely?

### ISSUE THREAD

**Issue by Nowaker** [bundler/gemstash#104]
> The gem dependencies from https://rubygems.org are cached for 30 minutes, so if you bundle again before that, you can successfully bundle without an Internet connection:

It's not clear to me what exactly happens.

1. Gem dependencies (what depends on what - the metadata) is cached for 30 minutes. Cached gems (*.gem files) are cached indefinitely.
2. Gem dependencies (that is, gems, as a dependency of a gem is another gem) is cached for 30 minutes. *.gem files disappear after 30 minutes.

Can you clarify here or, better yet, in the documentation itself?

---

Gemstash has saved my life. [Fastly seems to have a problem recently at DigitalOcean/Gitlab.com CI runners](https://github.com/rubygems/rubygems/issues/1701) and Gemstash helped the situation. Thanks for your great work.

**Comment by pcarranza** [comment]
What gets cached is the former option.

We cache the metadata for 30 minutes, gems are immutable, therefore they are cached indefinitely.

How could that be written in the documentation to make it clearer?

Glad to help you both with GL and Gemstash :)

**Comment by Nowaker** [comment]
I would phrase it like this:

> Gem files (*.gem) are caches indefinitely. The gem dependency metadata are cached for 30 minutes, so if you bundle again before that, you can successfully bundle without an Internet connection.

**Comment by smellsblue** [comment]
@Nowaker I committed this change but set you as the author: 339d84a246ac637664e1079c7e542860e508baa8

If you are ok with this, I'll create a PR for it :smile:

**Comment by Nowaker** [comment]
@smellsblue All is fine, thank you. :)
