### ISSUE TITLE
Expose Sequel options as configuration

### ISSUE THREAD

**Issue by chriseckhardt** [bundler/gemstash#115]
I ran into the following error running Gemstash in production (otherwise, it's been fantastic, so thank you!):

```
ERROR - 2016-10-27 21:24:56 - Sequel::PoolTimeout - timeout: 5.0, elapsed: 5.00085997:
```

I was able to get around this by modifying the database connection method invoked from `lib/gemstash/env.rb`, but maybe this should be something admins can set in config.yml?

**Comment by chriseckhardt** [comment]
More specifically, I set `max_connections: 17` (puma threads + 1). But other options listed in http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html might be beneficial as config options as well.

**Comment by olleolleolle** [comment]
@chriseckhardt Is this closable, now?

**Comment by chriseckhardt** [comment]
LGTM, thank you!
