### ISSUE TITLE
caching "built" gems

### ISSUE THREAD

**Issue by cjbottaro** [bundler/gemstash#144]
Not sure the terminology here, but would it possible for gemstash to install the "built" gems?  Really looking to cut down on `bundle install` time, which currently isn't happening.  So far from what I can tell, gemstash just acts as a local mirror for rubygems, but for the subset of gems that are in the lock file.  Is that right?

**Comment by smellsblue** [comment]
Correct, it just caches the gems you fetch through it. However you can also store your own private gems in it.

I'm not entirely sure what you are looking for exists, and it might come with some rather large risks.

I believe gems mostly just need to be unzipped to install them, with the exception of gems that have native compilation steps (like nokogiri for example).

If you want to try to cache this compilation step for native gems, you could run into issues if the machine you compile on differs from where you want to install them on. For example, the compilation could have macros that change how it compiles depending on the OS or hardware on the machine, or slight differences in installed libraries might cause unexpected failures in the gem.

If you are absolutely sure the machine you install on will match close enough to not cause issues, you could consider committing the installed gems on some sort of build server, then just check out those gems in the correct location on the target server... though, again, I think the risks would make this a scary solution.

**Comment by bronzdoc** [comment]
@cjbottaro is this still an issue for you?

**Comment by bronzdoc** [comment]
Closing for lack of response
