### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by dlackty** [bundler/gemstash#145]
When our team trying to deploy gemstash to our servers, we immediately found that there's no health check endpoint for load balancer to check.

Is there any existing endpoint for that purpose? Otherwise, is there any way to manually insert rack middleware?

I would like to help but I need your inputs. Thanks!

**Comment by olleolleolle** [comment]
@dlackty https://github.com/imajes/rack-heartbeat is an OK `GET /heartbeat` Rack middleware.

But, it seems you won't be able to inject more middleware on a stock Gemstash

https://github.com/bundler/gemstash/blob/af0fd04a0437e9fec9cc07f6d41333716046ed98/man/gemstash-customize.7.md#server

**Comment by dlackty** [comment]
I see. However, I would prefer https://github.com/mirakui/rack-health because its simplicity.
I would try to integrate and send out a PR soon.

**Comment by olleolleolle** [comment]
@smellsblue Has there been discussion on "how do I extend my Gemstash server with extra middleware"?

**Comment by smellsblue** [comment]
I've been a bit out of the loop lately due to work, vacation and now railsconf, but I'm definitely interested in both a health check and middleware (which I've played with a bit but don't have anything complete yet).

I think health check is important enough to be part of Gemstash directly. I'd be happy to help with a change or help get a PR merged!

**Comment by smellsblue** [comment]
By the way, my colleagues and I have made a health check set of gems that works with just rack (or rails for a separate gem).

Maybe we can utilize it here?

https://github.com/on-site/server_health_check-rack

**Comment by sandstrom** [comment]
Although opinionated, I think `/health` would be a good endpoint since it's quite common. But I'm happy with any endpoint name 😄

**Comment by smellsblue** [comment]
I still need to add documentation, but would #146 work? It checks that read and write works, but also has a heartbeat endpoint if you just want to ping the server.
