### ISSUE TITLE
sinatra show_exceptions settings

### ISSUE THREAD

**Issue by lionelperrin** [bundler/gemstash#149]
When started using gemstash start --no-daemonize, when trying to push twice the same gem for instance, I get a 160ko webpage with all the sinatra backtrace. I don't expect this behavior and would rather keep a basic error message.

Maybe I've missed an option to run the application with production settings instead of developer settings ?

Regards,

**Comment by adamvduke** [comment]
Have you tried settings the environment variable `RACK_ENV=production`?

**Comment by bronzdoc** [comment]
Closing due to lack of response
