### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by arhamahmed** [bundler/gemstash#151]
Hi, I'm currently developing a gem that has a dependency on gemstash, specifically the protected fetch feature. Protected fetch is not in the latest release so it is currently blocking me to release my gem. Could gemstash be updated to include it?

**Comment by olleolleolle** [comment]
@arhamahmed Can you `gem specific_install` it from Git? https://github.com/rdp/specific_install

**Comment by dazuma** [comment]
@olleolleolle specific_install works as a development workaround, but we don't want to force end users to run it. We need a specific release of gemstash that we can list as a gem dependency.

The protected fetch feature has been in master for more than a year (added in #94) but hasn't been part of a release. Is there a reason we're holding off on it?

**Comment by jules2689** [comment]
This has now been addressed 🎉 

https://twitter.com/bundlerio/status/892087085817094145
