### ISSUE TITLE
Feature: never expire anything

### ISSUE THREAD

**Issue by lukebigum** [bundler/gemstash#155]
Hello,

In _lib/gemstash/cache.rb_ there's a hardcoded expiry timer, and your docs say you only cache dependencies and metadata for 30 minutes.  I would be interested in setting an infinite expiry time on this data.  I would then be able to use Gemstash as an offline cache for Gems in our network, and if our Internet access went down, I'd still be able to get to the existing Gems I had cached.

Is this a feasible request?

**Comment by olleolleolle** [comment]
Would this PR resolve your request? #207

**Comment by bronzdoc** [comment]
closed by https://github.com/bundler/gemstash/pull/207
