### ISSUE TITLE
Functionality - using one source for cached and private gems

### ISSUE THREAD

**Issue by danfromtitan** [bundler/gemstash#166]
The problem I'm trying to solve is use one source URL for both cached and private gems. The reason for that is because I don't have control on the Gemfile in various projects that will source from Gemstash.

I was hoping this problem was already taken care of as I see some rewriting taking place in the logs, but fetching the private gems still requires /private in URL.

`Rewriting '/private/api/v1/dependencies?gems=my-gem' to '/api/v1/dependencies?gems=my-gem'`

Anyway, I though I'll work around this by forcing Gemstash to cache my private gem, so I bundled locally from a Gemfile such that my-gem will be source from localhost/private URL.

```
source "http://localhost/"
source "http://localhost/upstream/#{CGI.escape("http://localhost/private")}" do
  gem 'my-gem', '0.1.2'
end
```

It seems Gemstash cached my private gem indeed:

```
$ sudo ls -l  /var/gemstash/gem_cache/ 
localhost_ea033f2a0ee6dc9d989885050b5252fa
rubygems.org_17ac4526301fd97a7a1a9e64103d89f2
```

But now when I try to bundle from source "http://localhost" it tells me my-gem cannot be found in any of the gem sources listed.

I'm not sure why dependencies metadata doesn't resolve the locally cached gem. Is there an easier way to solve this problem ? It's hard for me to believe every Gemstash user would maintain multiple sources in their Gemfile.

**Comment by nothau** [comment]
Try this:

source "http://localhost/private" do
  gem 'my-gem', '0.1.2'
end

**Comment by danfromtitan** [comment]
Sure, I know I can download from /private, I mentioned already. Found a workaround, closing.

**Comment by nothau** [comment]
Ah sorry, didn't fully read.  What was your workaround?

**Comment by danfromtitan** [comment]
Run 'gem server' on the build server:
- bundle install community gems from Gemfile to dedicated path (it installs all gems in the list + dependencies)
- git clone, rake build local projects & gem install to same path as above (it install private gems + community deps)
The run gemstash as a cache pointing to the build server.

This is all meant to avoid pushing gems to gemstash because of its inability to service community and private gems from the same URL.

The only upset I have with that is client's gem install will attempt to 'GET /api/v1/dependencies' from gemstash, which in turn will ask it from gem server. For some reason 'gem server' returns HTTP/1.1 404 Not Found, but then client will default to 'GET /specs.4.8.gz' which works fine. Only a bunch of garbage left in gemstash logs...
