### ISSUE TITLE
Gemstash allows overriding published gems

### ISSUE THREAD

**Issue by mzruya** [bundler/gemstash#188]
Pushing an existing version of a gem fails the request (see https://github.com/bundler/gemstash/issues/99), This might imply that the operation failed, but it actually succeeds, the underlying gem code is replaced.

Pushing a gem involves:
1. Storing it (https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_pusher.rb#L31)
2. a DB transaction (https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_pusher.rb#L72)

The gem storage operation can succeed (overriding the actual code), but the database transaction fails, raising an `ExistingVersionError`.

### Option 1
We could perform the file system operation at the end of the database transaction.

#### Pros
- If the file system operation fails, the database transaction will rollback.
- If the database operations fails, an exception would be raised which would prevent the file system operation from happening

#### Cons
- If the database transaction fails to commit, we'll still override the file system storage.
- This solution requires ensuring that the file system operation is the last and single statement in the database transaction, this would be hard to enforce over time.

### Option 2
Don't override the file, check if it exists before persisting and raise if it does.

### Option 3
Store file names based on a unique identifier.

#### Pros
- This addresses the issue by ensuring files are never overridden by the server.

#### Cons
- Files will be left in storage, we could attempt to cleanup if an exception is raised, but it's not guaranteed.

Options 2 and 3 feel like the most robust approach.
I'm interested in fixing it, any thoughts on the best route?

**Comment by bronzdoc** [comment]
Thanks for bringing this issue at sigh,  i'll ivestigate and try to address it.
