### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by indirect** [bundler/gemstash#19]
How do I get this up and running as a server? How do I set it up to act as a local cache for Rubygems.org? How do I get it running as a local private gem server? Where is the database stored? Where are gems stored? How can I upgrade a running server? How can I transfer a running server to another machine?

**Comment by smellsblue** [comment]
@indirect for this and #20, should the instructions be markdown files in the repository, or wiki pages in the github project, or some blend of the 2?

**Comment by segiddins** [comment]
Markdown files please! That way we can track changes. And wikis are evil.

**Comment by indirect** [comment]
:
