### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by indirect** [bundler/gemstash#20]
If someone has followed the deployment instructions (#19) and there is a server running, how do I use it? What if I want all of the app servers in my data center to use it? What if I want all of the pairing machines in the office to use it? What if I'm a developer with a laptop who is only sometimes at the office where gemstash is running? What if my Gemfile has multiple sources? What if I'm using private gems hosted on gemstash?

How do I push a private gem? How do I yank a private gem? How do I authenticate to the private gem server? How are my private gems protected from randos getting them if they see the `source` line in my Gemfile?

**Comment by smellsblue** [comment]
Based on your questions @indirect, do we need to implement #24 before the first release? Currently, fetching gems from a Gemstash server requires no authentication, just pushing (and when yanking/unyanking is supported, those will be restricted as well)

**Comment by pcarranza** [comment]
Isn't this done too?

**Comment by pcarranza** [comment]
@indirect I think we are currently covering almost all the questions except for a few. Do you think this is enough for now?

> If someone has followed the deployment instructions (#19) and there is a server running, how do I use it?

https://github.com/bundler/gemstash/blob/master/README.md#setup

> What if I want all of the app servers in my data center to use it?
> What if I want all of the pairing machines in the office to use it?

https://github.com/bundler/gemstash/blob/master/docs/mirror.md

> What if my Gemfile has multiple sources?

https://github.com/bundler/gemstash/blob/master/docs/multiple_sources.md

> What if I'm using private gems hosted on gemstash?
> How do I push a private gem?
> How do I yank a private gem?

https://github.com/bundler/gemstash/blob/master/docs/private_gems.md

> How do I authenticate to the private gem server?

There is no authentication model implemented.

> How are my private gems protected from randos getting them if they see the source line in my Gemfile?

Bind to your local network, gemstash does not have any kind of auth mechanism for now.

> What if I'm a developer with a laptop who is only sometimes at the office where gemstash is running? 

Is bundler going to support the idea of open a tcp connection to check that gemstash is there?

**Comment by pcarranza** [comment]
I think this is all covered already and this one is lingering too much.

Since 1.0.0 has been released I'm closing this.

Anything missing, let's open a new issue.
