### ISSUE TITLE
v2.0.0 memory leak

### ISSUE THREAD

**Issue by juleea** [bundler/gemstash#219]
We recently upgraded to version to 2.0.0 and started seeing spikes in memory usage on our 32GB box and suspect a memory leak. Prior to the upgrade, our free memory hovered around 34% of total memory. Here's a graph of free memory - the upgrade occurred on late Jan 16:

![image](https://user-images.githubusercontent.com/1173077/51875221-f6e68300-2318-11e9-9cb4-511ceac5f63f.png)

Any thoughts/recommendations?

**Comment by sinneduy** [comment]
Any updates here?  Just wanted to check in on this.

**Comment by bronzdoc** [comment]
I'll set time this week to check this out, sorry for the delay

**Comment by bronzdoc** [comment]
@juleea what tool are you using to monitor and plot memory usage? and can you share the gemstash log over the time you see the increment in memory? thanks

**Comment by juleea** [comment]
@bronzdoc we're using datdog to monitor and visualize. I took a look at a 5 minute window where memory consumption increased by 10% and found these 5 statements each logged between 300 and 500 times (with various gem names in the REDACTED fields)

```
<14>1 2019-02-09T13:38:26.158106Z gemstash-1.zp.int App - - - [2019-02-09 13:38:25 +0000] - INFO - Rewriting '/private/api/v1/dependencies' to '/api/v1/dependencies'
<14>1 2019-02-09T13:38:27.159383Z gemstash-1.zp.int App - - - [2019-02-09 13:38:27 +0000] - INFO - Rewriting '/private/api/v1/dependencies?gems=REDACTED' to '/api/v1/dependencies?gems=REDACTED'
<14>1 2019-02-09T13:38:27.359687Z gemstash-1.zp.int App - - - [2019-02-09 13:38:27 +0000] - INFO - Querying dependencies: REDACTED
<14>1 2019-02-09T13:38:34.568819Z gemstash-1.zp.int App - - - [2019-02-09 13:38:34 +0000] - INFO - Fetching dependencies: REDACTED
<14>1 2019-02-09T13:39:59.709972Z gemstash-1.zp.int App - - - [2019-02-09 13:39:59 +0000] - INFO - Gem REDACTED exists, returning cached gem
```

**Comment by sinneduy** [comment]
bump?

**Comment by bronzdoc** [comment]
Thanks @juleea i'll ping you if i need another kind of info

@sinneduy please be patient.

**Comment by bronzdoc** [comment]
@juleea i'm back at this...

I just set a datadog agent in a fresh ubuntu box to test both versions, i just noticed the logs you sent me does not correspond to the date you upgraded Gemstash and the memory increment started, could you send me the logs of when the supposed leak started? thanks!
