### ISSUE TITLE
Private gems in the database?

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#22]
Just an idea I've done in previous Rails projects that I've found useful.

If we store the private gem files in the database as blobs, we get a few free benefits:
* The Gemstash server could be served as a cluster by just pointing to the same database
* Backing up or moving the Gemstash server is as simple as backing up or moving the database
* If you don't care about backing up or moving cached upstream gems, backing up or moving becomes **only** dealing with the database
* Storing of the private gems and necessary info along with the cached dependency information can be in a single transaction that will either succeed or fail atomically

Some possible downfalls:
* Potentially a bit more complex or startling to understand if you are new to the code
* A user might be confused trying to find the gems and not seeing them in the storage *(could be mitigated by also caching the files to disk)*
* You might get less throughput *(could be mitigated with caching in memory/disk)*
* The blob size would limit the gem size *(blobs could be specified to be pretty big though, so this is probably not be a real problem)*

If you all feel this might be worthwhile to implement, I'd be happy to implement it in a branch so you can see the results.

Maybe clustering a Gemstash server is not a useful use case, or maybe backing up or moving the directory is just as easy as with the database (though I think there being 1 less step has value).

We can discuss here before I do anything. I think if we are going with this plan, though, we should probably do it before the initial release, to avoid needing to migrate the files into the database.

**Comment by indirect** [comment]
My current idea for how to cluster a gemstash is actually different—run one instance of Gemstash, and have it be your authority on private gems. Then, run as many gemstash servers as you need to be mirrors, anywhere you want... and those act as pass-through caches for the "canonical" private gemstash server. So, for example, you might have a single gemstash that you run in a datacenter at `gems.mycompany.com`, and you put that in your Gemfile... then inside each datacenter, you use either DNS or Bundler mirroring to point the servers at a gemstash that is local to that datacenter. Does that seem like it does what you're hoping to accomplish with database-based gems?

**Comment by smellsblue** [comment]
That's an awesome idea for clustering!

Backing up is still one step simpler with database gems. Backup the database and you are done. With file store, you backup the database and also the file store. If you just backup the file store, you will have all the gems, but you won't have the authorized API keys, and you would need to run it through gemstash somehow to cache the dependency info again.

Is this benefit worth database gems?

**Comment by pcarranza** [comment]
I think I do not have a strong opinion on backing the files on a database.

I honestly don't think that the complexity is so huge when backing up the dump of the DB in a tar, and also including the gem files.

That said, in my experience I always liked to handle files in a filesystem. That simplifies things like getting the hash of a file, or changing properties, or even duplicating or deduplicating them, which in a database is... weird.

So, my only reasons are from the operational point of view rather than the technical, as I do not think that there is going to be such a huge throughput to collapse a database-as-a-file-system.

How would sqlite work in the condition of supporting these blobs? would it even be suitable for such a task or it makes sense to tell the user: to use private gems use a real database?

BTW: :+1: on @indirect idea of how to build the cluster.

**Comment by smellsblue** [comment]
I've only ever used SQLite to store files in a dev or test environment. I recall hitting some kind of encoding issue with Rails... I don't remember if I solved it by switching to postgres or monkeypatching, or some other hack, but I don't remember hitting any other walls with SQLite storing blobs.

If the user has a ton of private gems, I would probably be nervous to recommend sticking with SQLite.

However, it would be implemented such that the files would still be cached to disk also, so it might not pose a big problem.

**Comment by smellsblue** [comment]
I'm closing this... seems like the consensus is that it's probably not worth the added complexity :-)
