### ISSUE TITLE
Protected fetch

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#24]
We have push behind an API key, as will be yank and unyank.

Should fetching private gems support the key as well?

Will bundler send API key from rubygems config?

Should we add that to bundler if not?

Maybe we send a 401 and bundler can look for API key from rubygems config? Maybe specify API key name in config and it will use it automatically?

**Comment by taoza** [comment]
@smellsblue It would be great to see Gemstash start supporting authentication for fetch, even just a HTTP basic auth. But I guess if we need it today we should be able to just add `Rack::Auth::Basic` to https://github.com/bundler/gemstash/blob/master/lib/gemstash/config.ru?

**Comment by smellsblue** [comment]
@taoza my goal is to get the same API keys used for push/yank/unyank to be used for fetching as well, though maybe it would be an option you would have to enable. If you wrap Gemstash with Nginx, then that's probably the best place to put some auth at this point, unless you are already customizing the rackup file for other reasons.

I think some temporary documentation until this is baked in would be great! I'd be happy to accept a pull request if you have played with the config and would like to provide some samples :-)

**Comment by rjocoleman** [comment]
I've done some digging around here. I was not familiar with how RubyGems and Bundler handle auth... here are my findings:

* RubyGems `gem` supports `--key` on `yank`, `unyank` and `add gem`. The key is added as a `HTTP_AUTHORIZATION` header without modification.

* `gem` supports source with username and password specified e.g. `gem install example -s http://foo@localhost:9292/private`. These are basic auth encoded when presented to Gemstash

* Bundler, if a username is configured (via URI, config or env) uses it and the password to do basic auth (encoded username/password combo). Among other times this is used when fetching.

* Gemstash private source takes the `HTTP_AUTHORIZATION` header and treats it as an API key without modification.

If a key is specified as a http basic auth username (e.g. via `http://foo@localhost:9292/` or `bundle config localhost foo`) then it's presented as `request.env["HTTP_AUTHORIZATION"] = ""Basic Zm9vOg==""`, the hash is a base64 string, this decodes to `foo:` where the username is foo and the password is null.

To support protected fetch I see one _gemstash-modifications-only_ option:
* Gemstash should decode `HTTP_AUTHORIZATION` to a username and password pair if the string starts with `Basic`. If the key is set as `http://key@localhost:9292/` then username is checked against auth via `Gemstash::Authorization.check` and password would be disregarded as it will be null.

If this sounds like an appopriate strategey then the decisions that need to be made are:

1. Where should this handling of HTTP Basic auth happen - `Gemstash::Authorization.check`, or in the private source only?
2. key is set as username in the HTTP Basic auth and the password, if set, ignored (I think this represents the best UI for users).
3. what permissions should be created - a single `install` or a discrete `fetch` too?
4. does checking for auth on an install need to live behind a config flag?

I'm happy to work on this, I just want to make sure I'm going in the correct direction first.

**Comment by smellsblue** [comment]
@rjocoleman thanks for the interest and work!

I think the approach you describe sounds reasonable to me, though I would like to hear from @pcarranza as well.

In response to your questions:
1. I think it would be nice to keep `Gemstash::Authorization.check` being in terms of the API key alone, so I would prefer the extraction from basic auth be done outside that method. This could be a separate check method that does the extraction and calls `Gemstash::Authorization.check`, or perhaps some kind of parse basic auth method that returns the API key extracted from basic auth, or directly in the private source.
2. This seems reasonable to me.
3. I think you will want to use the permission in [serve_marshal](https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_source/private_source.rb#L69-L75), [serve_gem](https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_source/private_source.rb#L81-L86), [serve_specs](https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_source/private_source.rb#L92-L95), and [serve_prerelease_specs](https://github.com/bundler/gemstash/blob/master/lib/gemstash/gem_source/private_source.rb#L97-L100). The `serve_gem` method is the most important, since it is what actually returns the gem binary, but the others will return various gemspec information, so I would expect them all to be combined under the same permission. `fetch` seams like a reasonable name for the permission to me, since Gemstash doesn't really deal with the actual install of the gems.
4. I think enabling `fetch` authorization checking should probably be explicitly enabled, otherwise it would be a backward incompatible change that I wouldn't be comfortable releasing until `2.0.0`. We have [a way to configure](https://github.com/bundler/gemstash/blob/master/lib/gemstash/configuration.rb) Gemstash, so perhaps a new key of some kind like maybe `:protected_fetch`? The config gets saved to `~/.gemstash/config.yml` and can be set up via [`gemstash setup`](https://github.com/bundler/gemstash/blob/master/docs/reference.md#setup). I think it would probably make sense to add this as one of the things the setup command asks about.

**Comment by smellsblue** [comment]
@rjocoleman I just finished some refactoring of auth stuff in #92 and #93 (hope it doesn't affect any work you may have already done too much!)

**Comment by rjocoleman** [comment]
Thanks @smellsblue, I just got done with a first pass based on #92. I'll compare with #93 and adjust accordingly

**Comment by smellsblue** [comment]
This was fixed with #94
