### ISSUE TITLE
Support running without memcached

### ISSUE THREAD

**Issue by pcarranza** [bundler/gemstash#3]
Just for the sake of leanness. So you can pull and start for a quick test.

**Comment by smellsblue** [comment]
+1

We are also going to need a database to store private gem spec metadata. Should we support sqlite + maybe a hash backed cache? Should that be an easy deployment option, or should it default to something like postgres + memcached in a real environment?

**Comment by pcarranza** [comment]
The simplest possible implementation would be using sqlite (while keeping it persistent)

I think that initially I would like to have it running with no more configuration than just a folder where to store stuff.

If we need it to scale we can just change the back end. But start simple.

**Comment by smellsblue** [comment]
We can even avoid file directory configuration... ~/.gemstash I think would work ok, and we can store the database and any desired configuration there as well :-)

I'm going to start work on this now.

**Comment by pcarranza** [comment]
Even better, I like it :smile: 

We just need ~/.gemstash and inside one folder for whatever is in one depth (like the specs list, etc) and one for all the gems.

But we can just create this on start.

I'll continue (tomorrow) with the storage implementation with this in consideration.

**Comment by smellsblue** [comment]
@pcarranza perfect! You can use Gemstash::Env.base_dir to get the configured directory.

With my latest commit, `gemstash setup` will ask about a few (all optional) config options... right now just whether you want memcached or in memory cache (defaults to in memory), and where you want files stored (defaults to ~/.gemstash).

Config is currently always stored in ~/.gemstash/config.yml, but down the road we can add a global --config option to point to an alternate config location (if we want).

I'm going to push most stuff in Gemstash::Env to be retrievable from config.yml, but they are details that probably don't matter to most people, so they will remain undocumented for now (and `gemstash setup` won't ask about them).
