### ISSUE TITLE
Feel free to ransack stickler

### ISSUE THREAD

**Issue by copiousfreetime** [bundler/gemstash#4]
Many times I meant to add functionality to [stickler](https://github.com/copiousfreetime/stickler) to be a pass through cache for rubygems (https://github.com/copiousfreetime/stickler/issues/7). 

I'd just like to say, you are welcome to any and all of the code in stickler to help with this project. Stickler itself is a sinatra app that provides all the gem server functionality as a series of rack middlewares. You are welcome to take any and all code you want. If you you decide to use any of the code, I'm happy to re-license it as MIT (currently ISC).

If there is no interest, no worries. Just thought I would make the offer.

**Comment by smellsblue** [comment]
Awesome! Thanks so much! I'll poke around this week :-)

Any requests for how to go about attributions and re-licensing?

**Comment by copiousfreetime** [comment]
Oh, you know what, probably easiest if I just re-license stickler itself. I'll go through and do an update to it and then there's no problem. I'll stick a copyright / MIT blurb at the top of each file just so its clear you can use it. Then just take willy-nilly. Feel free to add an attribution to the README as you see fit.

**Comment by pcarranza** [comment]
Thanks a lot @copiousfreetime :smile:

**Comment by copiousfreetime** [comment]
@pcarranza @smellsblue Stickler is now reliscened as MIT in the repository, so use code as you see fit.
