### ISSUE TITLE
DB Migration policy?

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#43]
I added [a migration](https://github.com/bundler/gemstash/blob/master/lib/gemstash/migrations/03_version_full_name.rb) that altered an existing table originally created in [another migration](https://github.com/bundler/gemstash/blob/master/lib/gemstash/migrations/01_gem_dependencies.rb). The migration would be simplier if it was just folded into the original one, but it would require anyone with a Gemstash server to delete their database, migrate it manually, or otherwise deal with it. I think that is likely just a few test Gemstash instances right now amongst us, but I don't know for sure.

This brings up a question about DB migration policy... should we support someone cloning the repository against master and pulling the codebase and running from there? Or do we require they strictly go through the gem? I'm personally in favor of requiring they go through the gem, otherwise we would have to be super careful about any merges into master. This would allow me to merge the 2 migrations (maybe even all migrations into 1 migration?).

Thoughts?

Should I merge the 2 migrations? All 3 migrations? Leave as is and treat each migration going forward as if there is a production database in the wild?

**Comment by pcarranza** [comment]
Tricky, it really depends on how do we want to maintain the service.

My gut feeling is that we should keep each migration that is needed... once we release the first production version :smile: 

So, I am good if for now we just merge the migrations, and after releasing 1.0 we get serious about maintaining migrations as needed.

**Comment by indirect** [comment]
Agreed; it seems fine to rewrite migrations until we release a 1.0, and then we should provide backwards compatibility. Too bad we don't have Rails to give us a schema.rb, then this wouldn't be a problem :P

**Comment by pcarranza** [comment]
:laughing: Are you a rails evangelist @indirect ?

**Comment by smellsblue** [comment]
No code needed for this, and I've already merged a few of the migrations that would benefit from it.
