### ISSUE TITLE
Add support for mysql as DB backend

### ISSUE THREAD

**Issue by pcarranza** [bundler/gemstash#51]
Just that.

**Comment by pcarranza** [comment]
There is a problem with the auth key length, it is set to be unique with a length of 2056.

This ends up making mysql complain that the length of the key is larger than what mysql supports:

```
Database error: Mysql::Error: Specified key was too long; max key length is 767 bytes
```

I took the liberty of reducing the length of the key to 255 as it looks like the generated keys are 32 bytes long.

**Comment by waynerobinson** [comment]
Why can't MySQL just be set to use `text` rather than `varchar`?

**Comment by waynerobinson** [comment]
Never mind… I should've read this a little harder.
