### ISSUE TITLE
Gemstash command outputs

### ISSUE THREAD

**Issue by farukaydin** [bundler/gemstash#56]
Currently, ```gemstash start``` doesn't return any output, and ```gemstash stop``` returns ```Command stop sent success```.

I think it's better to return outputs like "Gemstash started/stopped successfully!". If you're :+1: on this, I can work on it.

**Comment by smellsblue** [comment]
Aboslutely, thanks! The stop output is coming from Puma, I think it's probably ok to leave that output and add the Gemstash output, unless it's trivial to block it.
