### ISSUE TITLE
How does Gemstash compare to Geminabox?

### ISSUE THREAD

**Issue by taoza** [bundler/gemstash#84]
Obviously Geminabox has been around for a while and Gemstash is relatively a new comer. It would be great to have a comparison on features, security, hosting setup etc. So the gem server shoppers can make a more informed decision on which one to pick.

**Comment by pcarranza** [comment]
PRs are welcome! :smile:

**Comment by pcarranza** [comment]
Closing this one as it has been lingering for a while.
