### ISSUE TITLE
Documentation and release sync

### ISSUE THREAD

**Issue by rjocoleman** [bundler/gemstash#96]
As mentioned on Slack..

Docs in master do not represent the currently available version.
At very least we can add a note to this effect and a link to releases?

As new features are added and documented a reference to their targeted version too?
eg "ERB support in YAML configuration file (0.2 and greater)" (although this means contributors need to have an idea of version numbers/releases or it's more work on release)

**Comment by smellsblue** [comment]
This is fixed with #109: documentation is now shipped within the gem, starting with `1.0.3`.
