### ISSUE TITLE
Raised exceptions should include an appropriate HTTP status code and respond better than a 500 error

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#99]
`Gemstash::GemPusher::ExistingVersionError` raises and triggers a raw 500 Sinatra error. It should instead have a more appropriate HTTP status code with a nicer response. This goes for all Gemstash exceptions that get raised.

**Comment by bronzdoc** [comment]
closed by https://github.com/bundler/gemstash/pull/190
